build:
    tests:
        override:
            - true

    nodes:
        tests:
            environment:
                php:
                    version: 7.4
                    pecl_extensions:
                        - zip
        analysis:
            environment:
                php:
                    version: 7.4
                    pecl_extensions:
                        - zip
            tests:
                override: [php-scrutinizer-run]
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            within:
                brackets: true
