build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            environment:
                php:
                    version: 7.4
                    pecl_extensions:
                        - zip
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: false
                    - js-scrutinizer-run
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
checks:
    javascript:
        no_var: true
        no_param_assign: true
        no_loop_var_assign: true
        no_implicit_undefined_return: true
        no_else_return: true
        no_alert: true
        eqeqeq: true
