language: php

php:
  - 7.1

services:
  - mysql

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - touch ./database/testing.sqlite
  - php artisan migrate --database=sqlite_testing --no-interaction

script:
  - vendor/bin/phpunit
