language: php
sudo: required
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

addons:
  chrome: stable

install:
  - rm .env.example
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - touch ./database/database.sqlite
  - php artisan key:generate
  - php artisan migrate --database=sqlite --no-interaction
  - npm install
  - npm run prod
  - travis_retry composer self-update
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk &
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose

after_success:
    - bash <(curl -s https://codecov.io/bash) -t c82aad14-75da-40f2-bb27-e539fe75af92
